use serde::{Deserialize, Serialize};

/// Role of the message sender
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// System instructions
    System,
    /// User input
    User,
    /// AI assistant response
    Assistant,
    /// Tool execution result
    Tool,
}

/// A message in the conversation
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Message {
    /// The role of the message author
    pub role: Role,

    /// The contents of the message
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    /// An optional name for the participant
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Tool calls generated by the model
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub tool_calls: Vec<ToolCall>,

    /// Tool call ID this message is responding to (for Tool role)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
}

impl Message {
    /// Create a new message
    pub fn new(role: Role, content: impl Into<String>) -> Self {
        Self {
            role,
            content: Some(content.into()),
            name: None,
            tool_calls: Vec::new(),
            tool_call_id: None,
        }
    }

    /// Create a system message
    pub fn system(content: impl Into<String>) -> Self {
        Self::new(Role::System, content)
    }

    /// Create a user message
    pub fn user(content: impl Into<String>) -> Self {
        Self::new(Role::User, content)
    }

    /// Create an assistant message
    pub fn assistant(content: impl Into<String>) -> Self {
        Self::new(Role::Assistant, content)
    }

    /// Create a tool result message
    pub fn tool_result(tool_call_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            role: Role::Tool,
            content: Some(content.into()),
            name: None,
            tool_calls: Vec::new(),
            tool_call_id: Some(tool_call_id.into()),
        }
    }

    /// Add a tool call to the message
    pub fn with_tool_call(mut self, tool_call: ToolCall) -> Self {
        self.tool_calls.push(tool_call);
        self
    }
}

/// Tool definition
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Tool {
    /// The name of the function to be called
    pub name: String,

    /// A description of what the function does
    pub description: String,

    /// The parameters the function accepts, described as a JSON Schema object
    pub parameters: serde_json::Value,
}

/// A call to a tool
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolCall {
    /// The ID of the tool call
    pub id: String,

    /// The type of the tool (currently only "function")
    pub r#type: String,

    /// The function that the model called
    pub function: FunctionCall,
}

/// Function call details
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct FunctionCall {
    /// The name of the function to call
    pub name: String,

    /// The arguments to call the function with, as a JSON string
    pub arguments: String,
}

/// Response from the AI provider
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionResponse {
    /// A unique identifier for the completion
    pub id: String,

    /// The object type (e.g., "chat.completion")
    pub object: String,

    /// The Unix timestamp (in seconds) of when the completion was created
    pub created: u64,

    /// The model used for completion
    pub model: String,

    /// The list of completion choices
    pub choices: Vec<Choice>,

    /// Usage statistics for the completion request
    pub usage: Option<Usage>,
}

/// A completion choice
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Choice {
    /// The index of the choice in the list of choices
    pub index: u32,

    /// The generated message
    pub message: Message,

    /// The reason the model stopped generating tokens
    pub finish_reason: Option<String>,
}

/// Token usage statistics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Usage {
    /// Number of tokens in the prompt
    pub prompt_tokens: u32,

    /// Number of tokens in the generated completion
    pub completion_tokens: u32,

    /// Total number of tokens used in the request (prompt + completion)
    pub total_tokens: u32,
}

/// Configuration for the model
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelConfig {
    /// Sampling temperature (0.0 to 2.0)
    pub temperature: Option<f32>,

    /// Maximum number of tokens to generate
    pub max_tokens: Option<u32>,

    /// Nucleus sampling probability
    pub top_p: Option<f32>,

    /// Frequency penalty (-2.0 to 2.0)
    pub frequency_penalty: Option<f32>,

    /// Presence penalty (-2.0 to 2.0)
    pub presence_penalty: Option<f32>,

    /// Stop sequences
    pub stop: Option<Vec<String>>,
}

impl Default for ModelConfig {
    fn default() -> Self {
        Self {
            temperature: Some(0.7),
            max_tokens: None,
            top_p: Some(1.0),
            frequency_penalty: Some(0.0),
            presence_penalty: Some(0.0),
            stop: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_message_creation() {
        let msg = Message::user("Hello");
        assert_eq!(msg.role, Role::User);
        assert_eq!(msg.content, Some("Hello".to_string()));

        let msg = Message::system("System");
        assert_eq!(msg.role, Role::System);

        let msg = Message::assistant("Hi");
        assert_eq!(msg.role, Role::Assistant);
    }

    #[test]
    fn test_tool_result_creation() {
        let msg = Message::tool_result("call_123", "result");
        assert_eq!(msg.role, Role::Tool);
        assert_eq!(msg.tool_call_id, Some("call_123".to_string()));
        assert_eq!(msg.content, Some("result".to_string()));
    }

    #[test]
    fn test_serialization() {
        let msg = Message::user("Hello");
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"role\":\"user\""));
        assert!(json.contains("\"content\":\"Hello\""));
    }

    #[test]
    fn test_tool_serialization() {
        let tool = Tool {
            name: "get_weather".to_string(),
            description: "Get weather".to_string(),
            parameters: json!({
                "type": "object",
                "properties": {
                    "location": {"type": "string"}
                }
            }),
        };
        let json = serde_json::to_string(&tool).unwrap();
        assert!(json.contains("get_weather"));
    }
}
